-- Create weekly_reflections table for storing AI-generated weekly summaries
-- This table stores weekly reflection data generated by AI analysis

CREATE TABLE IF NOT EXISTS weekly_reflections (
    id SERIAL PRIMARY KEY,
    user_email TEXT NOT NULL,
    week_start_date DATE NOT NULL,
    week_end_date DATE NOT NULL,
    summary_text TEXT NOT NULL,
    insights JSONB,                    -- Structured insights as JSON
    patterns JSONB,                    -- Weekly patterns as JSON
    recommendations JSONB,             -- AI recommendations as JSON
    data_summary JSONB,                -- Summary of underlying data used
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_weekly_reflections_user_email ON weekly_reflections(user_email);
CREATE INDEX IF NOT EXISTS idx_weekly_reflections_week_dates ON weekly_reflections(week_start_date, week_end_date);
CREATE INDEX IF NOT EXISTS idx_weekly_reflections_created_at ON weekly_reflections(created_at);

-- Enable Row Level Security
ALTER TABLE weekly_reflections ENABLE ROW LEVEL SECURITY;

-- Create policy for public access (for now)
CREATE POLICY "Enable all operations for all users" ON weekly_reflections FOR ALL USING (true);

-- Add comment to document the schema
COMMENT ON TABLE weekly_reflections IS 'AI-generated weekly reflections and insights for users';
COMMENT ON COLUMN weekly_reflections.week_start_date IS 'Start date of the week (Monday)';
COMMENT ON COLUMN weekly_reflections.week_end_date IS 'End date of the week (Sunday)';
COMMENT ON COLUMN weekly_reflections.summary_text IS 'Main AI-generated summary text';
COMMENT ON COLUMN weekly_reflections.insights IS 'Structured insights as JSON object';
COMMENT ON COLUMN weekly_reflections.patterns IS 'Weekly patterns analysis as JSON';
COMMENT ON COLUMN weekly_reflections.recommendations IS 'AI recommendations as JSON array';
COMMENT ON COLUMN weekly_reflections.data_summary IS 'Summary of underlying check-in and mood data used';
